# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

XCODE_VERSION = "15.1"

platform :ios do
  desc "Builds and executes all unit tests"
  lane :test do
      xcodes(version: XCODE_VERSION)

	  test_devices = [
	    "iPhone 4s",
	    "iPhone SE",
	    "iPhone 8 Plus",
	    "iPad Pro (10.5-inch)"
	  ]

	  # Run unit tests
	  run_tests(
	  	devices: test_devices,
	  	disable_concurrent_testing: true,
	  	output_style: "standard"
	  )

	  # UI.message("Derived data: #{lane_context[SharedValues::SCAN_GENERATED_PLIST_FILE]}")
	  
	  # sh("xcrun","xccov","view",lane_context[SharedValues::SCAN_GENERATED_PLIST_FILE])
  end
end
