//
//  TSDKSport.h
//  SDKPlayground
//
// Copyright (c) 2015 TeamSnap. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "TSDKCollectionObject.h"
#import "TSDKObjectsRequest.h"

@interface TSDKSport : TSDKCollectionObject

@property (nonatomic, assign) NSInteger hasShootouts; //Example: 0
@property (nonatomic, assign) NSInteger hasStatisticTemplate; //Example: 1
@property (nonatomic, weak) NSString *shootoutLabel; //Example: **NULL**
@property (nonatomic, weak) NSString *overtimeLabel; //Example: **NULL**
@property (nonatomic, assign) NSInteger hasCustomizedLanguage; //Example: 1
@property (nonatomic, assign) BOOL isNonSport; //Example: 0
@property (nonatomic, weak) NSString *overtimeAbbrev; //Example: **NULL**
@property (nonatomic, assign) NSInteger tracksPoints; //Example: 1
@property (nonatomic, assign) NSInteger hasOvertime; //Example: 0
@property (nonatomic, assign) NSInteger lowScoreWins; //Example: 0
@property (nonatomic, weak) NSString *shootoutAbbrev; //Example: **NULL**
@property (nonatomic, weak) NSString *name; //Example: Baseball
@property (nonatomic, assign) NSInteger tracksOvertimeLosses; //Example: 0


// Non-Autogenerated
-(NSString *)memberDescription;
-(NSString *)membersDescription;
-(NSString *)nonMemberDescription;
-(NSString *)nonMembersDescription;

@end
