//
//  TSDKTeamPreferences.h
//  SDKPlayground
//
// Copyright (c) 2015 TeamSnap. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "TSDKCollectionObject.h"
#import "TSDKObjectsRequest.h"

@interface TSDKTeamPreferences : TSDKCollectionObject

@property (nonatomic, weak) NSString *globalUniformAway; //Example:
@property (nonatomic, assign) BOOL marketplaceShowTab; //Example: 0
@property (nonatomic, assign) BOOL statisticsShowTab; //Example: 0
@property (nonatomic, weak) NSDate *createdAt; //Example: 2012-05-27T03:32:51Z
@property (nonatomic, weak) NSString *availabilityEventCutoff; //Example: **NULL**
@property (nonatomic, assign) NSInteger teamId; //Example: 1
@property (nonatomic, weak) NSString *teamMessage; //Example: <p><span style="font-size:
@property (nonatomic, assign) BOOL assignmentsShowTab; //Example: 1
@property (nonatomic, assign) BOOL isPaymentsPrivate; //Example: 0
@property (nonatomic, assign) NSInteger colorSchemeCd; //Example: 13
@property (nonatomic, weak) NSString *availabilitiesSortOrder; //Example: jersey
@property (nonatomic, assign) NSInteger shareAvailabilityNotes; //Example: 0
@property (nonatomic, assign) BOOL tslEnabled; //Example: 1
@property (nonatomic, weak) NSString *alternateSportName; //Example: Global Domination
@property (nonatomic, weak) NSString *assignmentsEnableFor; //Example: Games and Events
@property (nonatomic, assign) NSInteger paymentsIgnoreNonPlayers; //Example: 0
@property (nonatomic, weak) NSString *availabilityGameCutoff; //Example: **NULL**
@property (nonatomic, assign) BOOL filesShowTab; //Example: 1
@property (nonatomic, assign) BOOL availabilitiesShowTab; //Example: 1
@property (nonatomic, weak) NSString *currencySymbol; //Example: $
@property (nonatomic, assign) NSInteger assignmentsEnableForCode; //Example: 0
@property (nonatomic, assign) BOOL isCoed; //Example: 1
@property (nonatomic, assign) NSInteger tslPushEnabled; //Example: 1
@property (nonatomic, assign) NSInteger leagueControlledSettings; //Example: 0
@property (nonatomic, assign) NSInteger remindersSendGame; //Example: 0
@property (nonatomic, assign) NSInteger managerDefaultAvailability; //Example: 0
@property (nonatomic, assign) NSInteger tslScorePushEnabled; //Example: 1
@property (nonatomic, weak) NSString *introductionText; //Example: Hi,
@property (nonatomic, assign) NSInteger trackedItemsIgnoreNonPlayers; //Example: 0
@property (nonatomic, assign) NSInteger announcementAboveHomePhoto; //Example: 1
@property (nonatomic, assign) NSInteger globalUseInternationalDate; //Example: 0
@property (nonatomic, assign) BOOL teamMediaShowTab; //Example: 1
@property (nonatomic, weak) NSString *memberSortOrder; //Example: last
@property (nonatomic, assign) NSInteger tracksPoints; //Example: 0
@property (nonatomic, weak) NSString *teamHeadline; //Example: Welcome
@property (nonatomic, weak) NSString *skillLevel; //Example: Competitive
@property (nonatomic, assign) BOOL isYouth; //Example: 0
@property (nonatomic, weak) NSString *gender; //Example: Coed
@property (nonatomic, assign) NSInteger globalUseInternationalTime; //Example: 0
@property (nonatomic, assign) BOOL showDivisionStandings; //Example: 0
@property (nonatomic, weak) NSDate *updatedAt; //Example: 2015-09-30T05:00:03Z
@property (nonatomic, assign) NSInteger hideHeader; //Example: 0
@property (nonatomic, weak) NSString *ageGroup; //Example:
@property (nonatomic, assign) BOOL paymentsShowTab; //Example: 1
@property (nonatomic, assign) BOOL isTrackedItemsPrivate; //Example: 0
@property (nonatomic, weak) NSString *globalUniformHome; //Example:
@property (nonatomic, assign) NSInteger remindersSendEvent; //Example: 0
@property (nonatomic, assign) NSInteger trackedItemsIsPrivate; //Example: 0
@property (nonatomic, assign) BOOL trackedItemsShowTab; //Example: 1
@property (nonatomic, weak) NSURL *linkTeam;
@property (nonatomic, weak) NSURL *linkTeamPhoto;
@property (nonatomic, weak) NSURL *linkTeamLogo;


-(void)getTeamWithCompletion:(TSDKArrayCompletionBlock)completion;

// Not AutoGenerated:
-(void)getTeamPhotoWithCompletion:(TSDKImageCompletionBlock)completion;
-(void)getTeamLogoWithCompletion:(TSDKImageCompletionBlock)completion;

@end
