//
//  TeamSnapSDK.h
//  TeamSnapSDK
//
//  Created by Jason Rahaim on 1/29/15.
//  Copyright (c) 2015 TeamSnap. All rights reserved.
//

//! Project version number for TeamSnapSDK.
//extern double TeamSnapSDKVersionNumber;

//! Project version string for TeamSnapSDK.
//extern const unsigned char TeamSnapSDKVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import "PublicHeader.h"

#import "TSDKTeamSnap.h"
#import "TSDKRequestConfiguration.h"
#import "TSDKRequestConfiguration.h"
#import "TSDKCollectionQuery.h"
#import "TSDKCollectionCommand.h"
#import "TSDKCollectionJSON.h"
#import "TSDKCollectionObject.h"
#import "TSDKUser.h"
#import "TSDKTeam.h"
#import "TSDKEvent.h"
#import "TSDKMember.h"
#import "TSDKMemberEmailAddress.h"
#import "TSDKMemberPhoneNumber.h"
#import "TSDKContact.h"
#import "TSDKContactEmailAddress.h"
#import "TSDKContactPhoneNumber.h"
#import "TSDKTrackedItem.h"
#import "TSDKAssignment.h"
#import "TSDKAvailability.h"
#import "TSDKBroadcastEmail.h"
#import "TSDKBroadcastAlert.h"
#import "TSDKCustomDatum.h"
#import "TSDKCustomField.h"
#import "TSDKForumPost.h"
#import "TSDKForumTopic.h"
#import "TSDKLocation.h"
#import "TSDKmemberStatistic.h"
#import "TSDKOpponent.h"
#import "TSDKPlan.h"
#import "TSDKSport.h"
#import "TSDKStatistic.h"
#import "TSDKStatisticDatum.h"
#import "TSDKStatisticGroup.h"
#import "TSDKTeamFee.h"
#import "TSDKTeamPreferences.h"
#import "TSDKTeamStatistic.h"
#import "TSDKTrackedItemStatus.h"
#import "TSDKRootLinks.h"
#import "TSDKTslPhotos.h"
#import "TSDKPublicFeatures.h"
#import "TSDKTeamResults.h"
#import "TSDKInvitationFinder.h"
#import "TSDKCompletionBlockTypes.h"
#import "TSDKConstants.h"
#import "TSDKTeamMediaGroup.h"
#import "TSDKMemberPreferences.h"
#import "TSDKTeamMediumComment.h"
#import "TSDKForumSubscription.h"
#import "TSDKTeamMedium.h"
#import "TSDKMemberPayment.h"
#import "TSDKPaymentNote.h"
#import "TSDKMemberBalance.h"
#import "TSDKOpponentResults.h"
#import "TSDKEventStatistic.h"
#import "TSDKAvailabilityGroups.h"
#import "TSDKNotifications.h"
#import "TSDKMessage.h"
#import "TSDKMessageDatum.h"
#import "TSDKDivisionLocation.h"
#import "TSDKCountry.h"
#import "TSDKTimeZone.h"
#import "TSDKMessageRecipient.h"
#import "TSDKMessageSender.h"
#import "TSDKMemberPhoto.h"
#import "TSDKBackgroundUploadProgressMonitorDelegate.h"
#import "TSDKLeagueCustomDatum.h"
#import "TSDKLeagueCustomField.h"
#import "TSDKMemberAssignment.h"
#import "NSURL+TSDKConveniences.h"
#import "TSDKTslMetadatum.h"
#import "TSDKApnDevice.h"
#import "TSDKTslChat.h"
#import "TSDKTslScore.h"
#import "TSDKDivision.h"
#import "TSDKDivisionPreferences.h"
#import "NSString+TSDKPublicConveniences.h"
#import "TSDKSmsGateway.h"
